"""Testi della home "Non giro" (IT + EN). Solo fatti già presenti sul sito."""

WORKS = [
    # (youtube id, titolo, sottotitolo IT, sottotitolo EN, anno)
    ("N7Ta9EZstzA", "Showreel 2026", "Concept e regia", "Concept & direction", "2026"),
    ("ySthwmhR-y4", "GERD", "Webuild · Documentario", "Webuild · Documentary", ""),
    ("pbGWFFmW1Fc", "WeSearch", "Webuild", "Webuild", "2025"),
    ("r0N34NuRFZc", "Wake Up!", "AI & Concept", "AI & Concept", ""),
    ("zJ28dM8DRYo", "FILA F-Box", "Salone del Mobile", "Salone del Mobile", "2023"),
    ("fA3pBdKnWbo", "Prada Canali", "Fashion", "Fashion", ""),
    ("UYnvGmCuroQ", "Builderhero", "Webuild", "Webuild", ""),
    ("xv2S2flaYJQ", "Chopard", "Fashion spot", "Fashion spot", ""),
    ("z-GjfCZasFo", "Progetto Italia", "Salini Impregilo", "Salini Impregilo", ""),
    ("B4Rv_BOayx8", "Atomic Dream Dance", "Dell Ala · AI", "Dell Ala · AI", ""),
    ("YVLem2cHfoc", "Hands", "Canali · Director's cut", "Canali · Director's cut", ""),
    ("588LDT1c3zs", "Custodiamo il domani", "Tetra Pak", "Tetra Pak", ""),
]

BRANDS = "Prada · Nike · BMW · Volkswagen · Bugatti · Ray-Ban · Timberland · Converse · Diadora · FILA · Colmar · Canali · John Richmond · Jacob Cohen · Luisa Spagnoli · Polaroid · Lavazza · Tetra Pak · Allianz · Novartis · Sisal · TIM · Webuild"

T = {
    "it": {
        "title": "Alex Dallolio, regista a Milano | Video aziendali, brand film e AI",
        "description": "Regista a Milano. Trasformo il materiale che un'azienda ha già (archivio, girato, immagini di prodotto) in video aziendali e brand film, sul set o con l'AI generativa. Webuild, FILA, Prada, Canali.",
        "og_title": "Alex Dallolio. Non tutto va girato.",
        "og_description": "Giro quello che serve. Il resto esiste già, o lo creo con l'AI.",
        "h1": "Non tutto va <em>girato.</em>",
        "sub": "Giro quello che serve. Il resto esiste già, o lo creo con l'AI.",
        "role": "Alex Dallolio · Regista · Milano",
        "scroll": "Scorri ↓",
        "nav": ("Film", "Taccuino", "Contatti"),
        "raw": "", "film": "▶ FILM",
        "prev": "Film precedente", "next": "Film successivo",
        "legend": "La moviola gira da sola: il grezzo arriva da destra e sotto la testina diventa film. Clic sul film per guardarlo.",
        "facts": [
            ("Spot, documentari, fashion film, installazioni.", "Webuild da undici anni. FILA, Prada, Canali, Nike, Lavazza."),
            ("Si parte da quello che c'è.", "Archivio, girato di cantiere, immagini di prodotto."),
            ("L'AI dove serve.", "Per FILA FW26: tre film sul set, due senza set."),
        ],
        "links": [("Tutti i 30 film →", "/it/videos.html"), ("Taccuino →", "/it/ai-films.html"),
                  ("Video da archivio →", "/it/video-aziendali-da-archivio.html"),
                  ("Video con l'AI →", "/it/video-aziendali-ai.html"),
                  ("Webuild →", "/it/webuild-caso-studio.html"), ("FILA →", "/it/fila-fashion-film.html")],
        "tac_h": "Taccuino. <em>Appunti AI.</em>",
        "tac_all": ("Tutto il taccuino →", "/it/ai-films.html"),
        "tac_room": "Entra nella stanza →",
        "who_h": "Chi",
        "bio": "Alessandro Dallolio è nato a Torino e ha passato parte dell'infanzia in Asia. Fa immagini da sempre: disegno, pittura, collage, poi cinema, pubblicità, installazioni, intelligenza artificiale. Ha lavorato con Nike, Lavazza, Prada, BMW, Disney, e con Webuild da undici anni. Vive e lavora a Milano.",
        "clients_label": "Clienti",
        "agencies": "Agenzie: DLV, Young &amp; Rubicam, JWT, Leo Burnett, Armando Testa. TV: Mediaset, Rai, Sky, Fox.",
        "book": "Prenota una call ↗", "other_lang": ("English", "/"),
        "close": "Chiudi",
        "cta_h": "Mandami quello che hai.<br><em>Ti dico se dentro c'è un film.</em>",
        "cta_mail": "Scrivimi →",
    },
    "en": {
        "title": "Alex Dallolio, film director in Milan | Corporate films, brand films and AI",
        "description": "Film director in Milan. I turn the material a company already has (archive, footage, product images) into corporate and brand films, on set or with generative AI. Webuild, FILA, Prada, Canali.",
        "og_title": "Alex Dallolio. Not everything needs to be shot.",
        "og_description": "I shoot what is needed. The rest already exists, or I create it with AI.",
        "h1": "Not everything needs to be <em>shot.</em>",
        "sub": "I shoot what is needed. The rest already exists, or I create it with AI.",
        "role": "Alex Dallolio · Film director · Milan",
        "scroll": "Scroll ↓",
        "nav": ("Films", "Notebook", "Contact"),
        "raw": "", "film": "▶ FILM",
        "prev": "Previous film", "next": "Next film",
        "legend": "The editing table runs by itself: raw footage comes in from the right and becomes film under the playhead. Click the film to watch it.",
        "facts": [
            ("Commercials, documentaries, fashion films, installations.", "Webuild for eleven years. FILA, Prada, Canali, Nike, Lavazza."),
            ("We start from what exists.", "Archive, site footage, product images."),
            ("AI where it helps.", "For FILA FW26: three films on set, two without one."),
        ],
        "links": [("All 30 films →", "/videos.html"), ("Notebook →", "/ai-films.html"),
                  ("Films from existing footage →", "/corporate-films-from-existing-footage.html"),
                  ("AI brand films →", "/ai-brand-films.html"),
                  ("Webuild →", "/webuild-case-study.html"), ("FILA →", "/fila-fashion-films.html")],
        "tac_h": "Notebook. <em>AI sketches.</em>",
        "tac_all": ("The whole notebook →", "/ai-films.html"),
        "tac_room": "Enter the room →",
        "who_h": "Who",
        "bio": "Alessandro Dallolio was born in Turin and spent part of his childhood in Asia. He has always made images: drawing, painting, collage, then cinema, advertising, installations, artificial intelligence. He has worked with Nike, Lavazza, Prada, BMW, Disney, and with Webuild for eleven years. He lives and works in Milan.",
        "clients_label": "Clients",
        "agencies": "Agencies: DLV, Young &amp; Rubicam, JWT, Leo Burnett, Armando Testa. TV: Mediaset, Rai, Sky, Fox.",
        "book": "Book a call ↗", "other_lang": ("Italiano", "/it/"),
        "close": "Close",
        "cta_h": "Send me what you have.<br><em>I will tell you if there is a film inside.</em>",
        "cta_mail": "Email me →",
    },
}
