"""La stanza in inglese: /room/ è generata da /stanza/index.html sostituendo i testi.
Ogni coppia deve trovarsi nel file italiano: se manca, build.py si ferma (così non resta
italiano nascosto nella versione inglese dopo una modifica)."""

PAIRS = [
    ('<a class="lngs" href="/room/" hreflang="en">EN</a>', '<a class="lngs" href="/stanza/" hreflang="it">IT</a>'),
    ('<html lang="it">', '<html lang="en">'),
    ('<title>La stanza | Alex Dallolio</title>', '<title>The room | Alex Dallolio</title>'),
    ('content="Scrivi un sogno o un pensiero: la tua scrittura compare a mano su un foglio, e ti risponde un film del taccuino di Alex Dallolio. Oppure diventa un film unico."',
     'content="Write a dream or a thought: your words appear by hand on a sheet of paper, and a film from Alex Dallolio\'s notebook answers. Or it becomes a one-of-a-kind film."'),
    ('<link rel="canonical" href="https://www.alexdallolio.com/stanza/">', '<link rel="canonical" href="https://www.alexdallolio.com/room/">'),
    ('<meta property="og:title" content="La stanza · Alex Dallolio">', '<meta property="og:title" content="The room · Alex Dallolio">'),
    ('<meta property="og:description" content="Scrivi un sogno. Ti risponde un film.">', '<meta property="og:description" content="Write a dream. A film answers.">'),
    ('<meta property="og:url" content="https://www.alexdallolio.com/stanza/">', '<meta property="og:url" content="https://www.alexdallolio.com/room/">'),
    ('<a href="/it/">← Torna al sito</a>', '<a href="/">← Back to the site</a>'),
    ("♪ Suono: no</button>", "♪ Sound: off</button>"),
    ("btn.textContent = v ? '♪ Suono: sì' : '♪ Suono: no';", "btn.textContent = v ? '♪ Sound: on' : '♪ Sound: off';"),
    ('Trascina lo spazio per girarlo · rotella per avvicinarti', 'Drag the space to turn it · scroll to move closer'),
    ('Trascina col dito per girarlo · due dita per avvicinarti', 'Drag with a finger to turn it · two fingers to move closer'),
    ('<nav class="doors mono" id="porte" aria-label="Le altre stanze"><span>Le altre stanze</span><a href="/it/#film">La moviola</a><a href="/it/ai-films.html">Il taccuino</a><a href="/it/videos.html">Tutti i film</a><a href="/it/#chi">Chi sono</a></nav>',
     '<nav class="doors mono" id="porte" aria-label="The other rooms"><span>The other rooms</span><a href="/#film">The editing table</a><a href="/ai-films.html">The notebook</a><a href="/videos.html">All films</a><a href="/#chi">About me</a></nav>'),
    ('Scrivi qualcosa. <span>Un sogno, un\'idea, un pensiero.</span>', 'Write something. <span>A dream, an idea, a thought.</span>'),
    ('aria-label="Foglio: scrivi qui"', 'aria-label="Sheet: write here"'),
    ('<span class="g-mouse">Scrivi con la tastiera</span><span class="g-touch">Tocca il foglio per scrivere</span>',
     '<span class="g-mouse">Type on your keyboard</span><span class="g-touch">Tap the sheet to write</span>'),
    ('>Fatto →</button>', '>Done →</button>'),
    ('Hai un sogno da vedere? <button type="button" data-open="commission">Lo trasformo in un film unico, da 150 €</button>',
     'Have a dream you want to see? <button type="button" data-open="commission">I turn it into a one-of-a-kind film, from €150</button>'),
    ('aria-label="Scrivi qui"', 'aria-label="Write here"'),
    ('>← Torna al foglio</button>', '>← Back to the sheet</button>'),
    ('Dalle tue parole, un film del mio taccuino', 'From your words, a film from my notebook'),
    ("Fanne un'opera unica · da 150 €", 'Make it a one-of-a-kind film · from €150'),
    ('data-open="note">Mandamelo</button>', 'data-open="note">Send it to me</button>'),
    ('id="again">Scrivi un altro foglio</button>', 'id="again">Write another sheet</button>'),
    ('<a href="/it/#film">La moviola →</a>', '<a href="/#film">The editing table →</a>'),
    ('aria-label="Chiudi">×</button>\n    <button type="button" class="back2">← Indietro</button>\n    <h2 id="c-t">',
     'aria-label="Close">×</button>\n    <button type="button" class="back2">← Back</button>\n    <h2 id="c-t">'),
    ('Un sogno, un film. <em>Opera unica.</em>', 'A dream, a film. <em>One of a kind.</em>'),
    ("<p>Un sogno, un ricordo, un'immagine che hai in testa e non puoi fotografare. Scrivimela: la trasformo in un film di una sola scena, da 10 a 20 secondi. Ogni film esiste in un solo esemplare ed è tuo. Nella versione Opera arriva con un certificato di unicità firmato a mano.</p>",
     "<p>A dream, a memory, an image in your head that no camera can take. Write it to me: I turn it into a film of a single scene, 10 to 20 seconds long. Each film exists in one copy only, and it is yours. The Artwork version comes with a certificate of uniqueness, signed by hand.</p>"),
    ('value="Appunto, 150 €" required><b>150 €</b><span>Appunto</span><small>Una scena di 10 secondi</small>',
     'value="Sketch, €150" required><b>€150</b><span>Sketch</span><small>A 10-second scene</small>'),
    ('value="Scena, 250 €"><b>250 €</b><span>Scena</span><small>20 secondi, con suono</small>',
     'value="Scene, €250"><b>€250</b><span>Scene</span><small>20 seconds, with sound</small>'),
    ('value="Opera, 350 €"><b>350 €</b><span>Opera</span><small>20 secondi, suono e certificato di unicità firmato a mano</small>',
     'value="Artwork, €350"><b>€350</b><span>Artwork</span><small>20 seconds, sound and a hand-signed certificate of uniqueness</small>'),
    ('for="c-p">Il tuo sogno, o il tuo pensiero</label>', 'for="c-p">Your dream, or your thought</label>'),
    ('for="c-e">La tua email</label>', 'for="c-e">Your email</label>'),
    ('for="c-n">Nome (facoltativo)</label>', 'for="c-n">Name (optional)</label>'),
    ("<p class=\"small\">Leggo ogni pensiero. Se ci vedo un film ti scrivo io con i tempi e il pagamento; se no, te lo dico. Paghi solo se accetto. Il film lo mostro nel mio taccuino solo se sei d'accordo. Uso la tua email solo per risponderti.</p>",
     "<p class=\"small\">I read every thought. If I see a film in it, I write back with timing and payment; if not, I tell you. You only pay if I accept. I show the film in my notebook only if you agree. I use your email only to reply to you.</p>"),
    ('class="send">Manda il pensiero</button>', 'class="send">Send the thought</button>'),
    ('aria-label="Chiudi">×</button>\n    <button type="button" class="back2">← Indietro</button>\n    <h2 id="n-t">',
     'aria-label="Close">×</button>\n    <button type="button" class="back2">← Back</button>\n    <h2 id="n-t">'),
    ('Mandalo <em>a me.</em>', 'Send it <em>to me.</em>'),
    ("<p>Un'idea, una domanda, un pensiero: arriva a me, così come l'hai scritto.</p>", "<p>An idea, a question, a thought: it reaches me just as you wrote it.</p>"),
    ('for="n-p">Il tuo foglio</label>', 'for="n-p">Your sheet</label>'),
    ('for="n-e">La tua email (se vuoi una risposta)</label>', 'for="n-e">Your email (if you want a reply)</label>'),
    ('<p class="small">Uso la tua email solo per risponderti.</p>', '<p class="small">I use your email only to reply to you.</p>'),
    ('class="send">Manda</button>', 'class="send">Send</button>'),
    ("msg.textContent = 'Invio…';", "msg.textContent = 'Sending…';"),
    ("'Ricevuto. Ti ho mandato una copia del tuo sogno: lo leggo e ti rispondo io.' : 'Ricevuto. Lo leggo e ti rispondo io.'",
     "'Received. I sent you a copy of your dream: I will read it and write back.' : 'Received. I will read it and write back.'"),
    ("'Arrivato. Ti ho mandato una copia del tuo foglio.' : 'Arrivato. Grazie.'", "'It arrived. I sent you a copy of your sheet.' : 'It arrived. Thank you.'"),
    ("'Troppi invii ravvicinati. Riprova tra un minuto.'", "'Too many messages in a row. Try again in a minute.'"),
    ("'Controlla i campi: serve un testo di almeno tre lettere e un\\'email valida.'", "'Check the fields: write at least three letters and a valid email.'"),
    ("msg.innerHTML = 'Non è partito. Riprova, oppure scrivimi a <a", "msg.innerHTML = 'It did not go through. Try again, or write to me at <a"),
    ("· clic per l'audio</span>", "· click for sound</span>"),
    ("lb.innerHTML = '<button type=\"button\" aria-label=\"Chiudi\">×</button>", "lb.innerHTML = '<button type=\"button\" aria-label=\"Close\">×</button>"),
    ('<script type="module" src="foglio3d.js"></script>', '<script type="module" src="/stanza/foglio3d.js"></script>'),
]
